/** @type {import('../api/gemini.js').Packet[]} Fallback dataset — 20 safe, 7 HTTP, 7 typosquatting, 6 phishing. */
export const FALLBACK_PACKETS = [
  // —— 20 SAFE (HTTPS, threatType safe) ——
  {
    id: 'pkt_001',
    protocol: 'HTTPS',
    domain: 'agency-portal.gov',
    payload: 'Encrypted login token refresh for analyst workstation session.',
    destination: 'Internal Auth Server',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, this is routine encrypted traffic to our internal authentication tier. The protocol and destination align with policy.',
    difficulty: 1,
  },
  {
    id: 'pkt_002',
    protocol: 'HTTPS',
    domain: 'ops-central.gov',
    payload: 'Scheduled ops report upload — weekly situational awareness digest.',
    destination: 'HQ File Archive',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, encrypted file transfer to the archive matches standard reporting windows. Nothing here suggests exfiltration.',
    difficulty: 1,
  },
  {
    id: 'pkt_003',
    protocol: 'HTTPS',
    domain: 'secure-hq.net',
    payload: 'VPN handshake renewal for field laptop cluster Delta-4.',
    destination: 'Perimeter Gateway East',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, VPN control plane traffic is expected on this subnet during shift changes.',
    difficulty: 2,
  },
  {
    id: 'pkt_004',
    protocol: 'HTTPS',
    domain: 'intel-hub.gov',
    payload: 'Bulk metadata sync for counter-intel watchlists (redacted headers).',
    destination: 'Analytics Mesh Node 2',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, the destination is an approved analytics node; HTTPS protects the payload in transit.',
    difficulty: 2,
  },
  {
    id: 'pkt_005',
    protocol: 'HTTPS',
    domain: 'clearance-api.gov',
    payload: 'Officer badge validation request from lobby terminal B-12.',
    destination: 'Physical Access Controller',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, physical access checks routinely hit the controller over TLS. Domain and path are consistent.',
    difficulty: 1,
  },
  {
    id: 'pkt_006',
    protocol: 'HTTPS',
    domain: 'sat-link.mil',
    payload: 'Ephemeris update for secure timing channel — navigation aid bundle.',
    destination: 'Orbital Timing Service',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, timing data is sensitive but appropriately encrypted here; destination naming matches infrastructure docs.',
    difficulty: 3,
  },
  {
    id: 'pkt_007',
    protocol: 'HTTPS',
    domain: 'personnel-roster.internal',
    payload: 'Delta roster diff — adds/removals since midnight UTC.',
    destination: 'HR Systems Bridge',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, roster deltas over HTTPS to the HR bridge are normal during redeployments.',
    difficulty: 2,
  },
  {
    id: 'pkt_008',
    protocol: 'HTTPS',
    domain: 'evidence-locker.gov',
    payload: 'Chain-of-custody heartbeat for exhibit W-4412.',
    destination: 'Forensics Storage Tier A',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, custody heartbeats protect integrity; this path is whitelisted for evidence systems.',
    difficulty: 1,
  },
  {
    id: 'pkt_009',
    protocol: 'HTTPS',
    domain: 'wire-room.secure',
    payload: 'Low-latency voice metadata (no content) for compliance logging.',
    destination: 'Lawful Intercept Logger',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, metadata-only logging is policy-compliant when TLS terminates correctly at the logger.',
    difficulty: 3,
  },
  {
    id: 'pkt_010',
    protocol: 'HTTPS',
    domain: 'supply-chain.trust',
    payload: 'Vendor attestation token for laptop shipment batch 88-C.',
    destination: 'Procurement Verification',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, hardware attestations should be encrypted; this packet meets that bar.',
    difficulty: 2,
  },
  {
    id: 'pkt_011',
    protocol: 'HTTPS',
    domain: 'briefing-deck.gov',
    payload: 'Slide deck sync for division stand-up — classification: confidential.',
    destination: 'Collaboration Share',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, internal collaboration shares require HTTPS; this is an expected sync pattern.',
    difficulty: 1,
  },
  {
    id: 'pkt_012',
    protocol: 'HTTPS',
    domain: 'threat-feed.api',
    payload: 'STIX bundle pull — latest IOC list revision 2026.04.18.',
    destination: 'Threat Intel Aggregator',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, pulling STIX over TLS from the aggregator is how we keep sensors current.',
    difficulty: 2,
  },
  {
    id: 'pkt_013',
    protocol: 'HTTPS',
    domain: 'patch-window.hq',
    payload: 'Windows patch manifest signature verification request.',
    destination: 'Endpoint Management Core',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, patch manifests must be signed and delivered over HTTPS — this matches hygiene controls.',
    difficulty: 1,
  },
  {
    id: 'pkt_014',
    protocol: 'HTTPS',
    domain: 'travel-auth.gov',
    payload: 'Temporary duty itinerary approval for Agent Morales.',
    destination: 'Travel Office Workflow',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, travel workflow traffic is boring but legitimate when encrypted end-to-end.',
    difficulty: 2,
  },
  {
    id: 'pkt_015',
    protocol: 'HTTPS',
    domain: 'biometrics-enroll.secure',
    payload: 'Template hash upload — no raw images, hashed minutiae only.',
    destination: 'Identity Proofing Vault',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, biometric templates must never traverse HTTP; here they do not.',
    difficulty: 3,
  },
  {
    id: 'pkt_016',
    protocol: 'HTTPS',
    domain: 'dr-site.failover',
    payload: 'Warm-standby database checkpoint ping — DR drill idle state.',
    destination: 'Disaster Recovery SQL',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, DR heartbeats are low risk but still merit TLS — present here.',
    difficulty: 2,
  },
  {
    id: 'pkt_017',
    protocol: 'HTTPS',
    domain: 'key-escrow.internal',
    payload: 'Quarterly split-key ceremony schedule publication.',
    destination: 'Crypto Operations Desk',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, key ceremony announcements are sensitive scheduling data — HTTPS is appropriate.',
    difficulty: 3,
  },
  {
    id: 'pkt_018',
    protocol: 'HTTPS',
    domain: 'unclass-relay.gov',
    payload: 'Public affairs press kit sync — already approved for release.',
    destination: 'External CDN Edge',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, even unclassified bundles should ride TLS to prevent tampering in transit.',
    difficulty: 1,
  },
  {
    id: 'pkt_019',
    protocol: 'HTTPS',
    domain: 'lab-results.hospital-partner',
    payload: 'Encrypted health summary for cleared medical officer (minimum necessary).',
    destination: 'Medical Liaison Inbox',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, partner health data is protected in transit; routing matches liaison workflow.',
    difficulty: 2,
  },
  {
    id: 'pkt_020',
    protocol: 'HTTPS',
    domain: 'fleet-telematics.trust',
    payload: 'Armored convoy GPS breadcrumb batch — 30-second granularity.',
    destination: 'Transport Operations Map',
    isMalicious: false,
    threatType: 'safe',
    explanation:
      'Agent, convoy telemetry is operationally sensitive; HTTPS keeps it off open radio analysis.',
    difficulty: 3,
  },

  // —— 7 HTTP_UNENCRYPTED ——
  {
    id: 'pkt_021',
    protocol: 'HTTP',
    domain: 'agency-portal.gov',
    payload: 'Password hash retransmit after session glitch — user awaiting re-auth.',
    destination: 'Internal Auth Server',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, the domain looks fine but HTTP means this data travels in plain text. Enemy signals intelligence can intercept every byte of that password hash.',
    difficulty: 1,
  },
  {
    id: 'pkt_022',
    protocol: 'HTTP',
    domain: 'ops-central.gov',
    payload: 'Quarterly budget spreadsheet — contains embedded credential tabs.',
    destination: 'HQ File Archive',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, HTTP exposes spreadsheet contents on the wire. Even “internal” paths can be tapped on a compromised switch.',
    difficulty: 1,
  },
  {
    id: 'pkt_023',
    protocol: 'HTTP',
    domain: 'intel-hub.gov',
    payload: 'Sensitive witness statement PDF — OCR text layer included.',
    destination: 'Case Management Server',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, witness statements demand confidentiality. Without TLS, content is readable to anyone on the path.',
    difficulty: 2,
  },
  {
    id: 'pkt_024',
    protocol: 'HTTP',
    domain: 'clearance-api.gov',
    payload: 'PII lookup: home addresses for watchlist cross-check.',
    destination: 'Identity Resolution Engine',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, PII must never leave the station unencrypted. HTTP here is an automatic quarantine case.',
    difficulty: 2,
  },
  {
    id: 'pkt_025',
    protocol: 'HTTP',
    domain: 'briefing-deck.gov',
    payload: 'Encrypted-looking filename, but raw HTTP body — deck contains facility maps.',
    destination: 'Collaboration Share',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, filenames can lie. The transport is HTTP, so the maps are not protected in flight.',
    difficulty: 3,
  },
  {
    id: 'pkt_026',
    protocol: 'HTTP',
    domain: 'travel-auth.gov',
    payload: 'Passport number verification packet for expedited visa.',
    destination: 'Travel Office Workflow',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, travel identifiers in cleartext are a gift to border-adjacent adversaries sniffing Wi‑Fi uplinks.',
    difficulty: 2,
  },
  {
    id: 'pkt_027',
    protocol: 'HTTP',
    domain: 'patch-window.hq',
    payload: 'Kerberos ticket fragment for legacy app — still sensitive.',
    destination: 'Endpoint Management Core',
    isMalicious: true,
    threatType: 'http_unencrypted',
    explanation:
      'Agent, authentication material over HTTP lets an attacker replay or forge sessions. Block and escalate.',
    difficulty: 3,
  },

  // —— 7 TYPOSQUATTING ——
  {
    id: 'pkt_028',
    protocol: 'HTTPS',
    domain: 'agency-porta1.gov',
    payload: 'URGENT: Director calendar sync — accept now to avoid lockout.',
    destination: 'Mail Gateway Cluster',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, the domain swapped a lowercase L for the numeral 1 in “portal.” The TLS padlock does not prove the hostname is ours.',
    difficulty: 1,
  },
  {
    id: 'pkt_029',
    protocol: 'HTTPS',
    domain: 'g0v-secure.net',
    payload: 'Mandatory security questionnaire — complete within 5 minutes.',
    destination: 'Survey Collector',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, “gov” was replaced with “g0v” — letter O to zero. That one glyph routes traffic outside authentic government DNS.',
    difficulty: 1,
  },
  {
    id: 'pkt_030',
    protocol: 'HTTPS',
    domain: 'agenxy-portal.gov',
    payload: 'New device enrollment token — tap to trust this endpoint.',
    destination: 'Mobile Device Lab',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, an extra “x” crept into “agency.” Typosquatters bank on fast reads during bursts of traffic.',
    difficulty: 2,
  },
  {
    id: 'pkt_031',
    protocol: 'HTTPS',
    domain: 'agencyportal.gov',
    payload: 'Policy acknowledgment banner — click-through required today.',
    destination: 'Web Front Door',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, the hyphen between “agency” and “portal” vanished. Legit bookmarks use the punctuated form.',
    difficulty: 2,
  },
  {
    id: 'pkt_032',
    protocol: 'HTTPS',
    domain: 'agency-portal.com',
    payload: 'Encrypted benefits enrollment — HR says finish before COB.',
    destination: 'HR Systems Bridge',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, we operate on .gov for this service. A .com twin is a classic TLD swap lure.',
    difficulty: 2,
  },
  {
    id: 'pkt_033',
    protocol: 'HTTPS',
    domain: 'agency-protal.gov',
    payload: 'VPN token rotation — hurry before token expires.',
    destination: 'Perimeter Gateway West',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, “portal” became “protal” — letters R and O transposed. HTTPS cannot fix a wrong host.',
    difficulty: 3,
  },
  {
    id: 'pkt_034',
    protocol: 'HTTPS',
    domain: 'login.agency-portal.gov.malicious.io',
    payload: 'Re-verify SSO cookie — routine maintenance window.',
    destination: 'Identity Broker',
    isMalicious: true,
    threatType: 'typosquatting',
    explanation:
      'Agent, the registrable domain here is malicious.io. Everything before it is decoration meant to mimic our portal.',
    difficulty: 3,
  },

  // —— 6 PHISHING ——
  {
    id: 'pkt_035',
    protocol: 'HTTPS',
    domain: 'agency-portal.gov',
    payload:
      'URGENT: Agency director password reset required immediately — do not delay.',
    destination: '185.220.101.47',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, the domain looks perfect, but the destination is a Tor-adjacent exit node IP. Always verify where traffic actually lands.',
    difficulty: 1,
  },
  {
    id: 'pkt_036',
    protocol: 'HTTPS',
    domain: 'ops-central.gov',
    payload: 'CRITICAL: Multi-factor auth token expiring — click to re-authenticate now.',
    destination: 'redirect: 92.63.196.99',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, urgency is a lever. The IP is external and unrelated to ops-central infrastructure — classic credential theft routing.',
    difficulty: 1,
  },
  {
    id: 'pkt_037',
    protocol: 'HTTPS',
    domain: 'secure-hq.net',
    payload: 'ACTION REQUIRED: Verify your identity or access will be suspended in 10 minutes.',
    destination: 'unknown external endpoint',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, the hostname is vague on purpose. Coupled with panic language, this is phishing even over HTTPS.',
    difficulty: 2,
  },
  {
    id: 'pkt_038',
    protocol: 'HTTPS',
    domain: 'intel-hub.gov',
    payload: 'Wire instructions for classified courier payment — CFO approved.',
    destination: '103.45.167.88',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, financial redirects to unfamiliar IPs are never normal for intel-hub. Verify out-of-band before any allow.',
    difficulty: 2,
  },
  {
    id: 'pkt_039',
    protocol: 'HTTPS',
    domain: 'clearance-api.gov',
    payload: 'Please confirm your desk token serial for the annual inventory.',
    destination: '10.66.99.1',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, the IP sits outside documented RFC1918 ranges we use internally — it only looks “sort of” internal.',
    difficulty: 3,
  },
  {
    id: 'pkt_040',
    protocol: 'HTTPS',
    domain: 'personnel-roster.internal',
    payload: 'Kindly review your W-2 preview before payroll finalizes tonight.',
    destination: 'payroll-harvest.ru',
    isMalicious: true,
    threatType: 'phishing',
    explanation:
      'Agent, the sender domain feels right, but the destination TLD screams compromise. Tax data must never route there.',
    difficulty: 3,
  },
];
